### ISSUE TITLE
Loading / navigation seems slow

### ISSUE THREAD

**Issue by jennybc** [rstudio/r-manuals#8] opened 2022-10-31 22:34 UTC
This will be frustrating in its lack of specifics. But I generally perceive that the manual sites are "slow". To be more specific, the one I only interact with much is the [Writing R Extensions](https://rstudio.github.io/r-manuals/r-exts/). I don't really know why that would be :thinking: But I've noticed it enough times, over a reasonably long time period, that I wanted to raise it.

We generally use GitHub Pages for pkgdown sites and I haven't noticed similar slowness there. So I'm not sure if there's any point in considering deployment to, say, Netlify.

Can those of you with more knowledge of the project speculate if there's anything about its structure that might explain the slowness? Of course, it's possible that I'm just getting unlucky.

**Comment by jennybc** [comment] 2022-10-31 22:55
I get a lot of behaviour where it just feels like page loading is hung / stalled.

![Screen Shot 2022-10-31 at 3 34 57 PM](https://user-images.githubusercontent.com/599454/199122933-d09b090d-e816-41ef-944e-83681f773b03.png)

Maybe it's just this specific page? It's quite large compared to most others.

https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html

**Comment by andrie** [comment] 2022-11-09 10:26
My understanding is this only manifests when using the Safari browser.  The quarto dev team have been able to reproduce this, and have identified potential fixes that may be resolved in a future release of quarto.

I'm going to close this issue here, since the actual problem is upstream.

**Closed as completed by andrie** 2022-11-09 10:26 UTC
